spring:
  application:
    name: persistance
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true